databases:
  - name: insidertrading
    databaseName: insidertrading
    user: insidertrading

services:
  - type: web
    name: insidertrading
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn insidertrading.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: insidertrading
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4