databases:
  - name: insider
    databaseName: insider
    user: insider

services:
  - type: web
    name: insider
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn insider.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: insider
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4